# Generated by Django 4.2 on 2023-05-30 02:08
from sqlite3 import IntegrityError

from django.db import migrations, transaction


def create_categories(app, *args):
    try:
        with transaction.atomic():
            Category = app.get_model('confApp', 'Category')
            Category.objects.create(name='Deportes', description='Noticias relacionadas con las actividades deportivas')
            Category.objects.create(name='Centro de Estudiantes',
                                    description='Noticias relacionadas con el centro de estudiantes')
            Category.objects.create(name='General', description='Noticias generales')
    except IntegrityError:
        print("--------------ERROR--------------")


class Migration(migrations.Migration):
    dependencies = [
        ('confApp', '0004_alter_new_body'),
    ]

    operations = [
        migrations.RunPython(create_categories)
    ]
